// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Pengeplan.Core;

namespace Pengeplan.iOS
{
	public partial class TransactionTableViewController : UITableViewController
	{
		public TransactionsViewModel viewModel = ServiceContainer.Resolve<TransactionsViewModel> ();

		public TransactionTableViewController (IntPtr handle) : base (handle)
		{
		}

		public override  int RowsInSection (UITableView tableView, int section)
		{
			return viewModel.NumberOfItems ();
		}

		public override  UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			string cellIdentifier = "TableCell";

			UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier) ?? new UITableViewCell (UITableViewCellStyle.Value1, cellIdentifier);
			cell.TextLabel.Text = viewModel.LeftCellContent (indexPath.Row);
			cell.DetailTextLabel.Text = viewModel.RightCellContent (indexPath.Row);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
