// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Pengeplan.iOS
{
	public partial class OverViewController : UIViewController
	{
		public OverViewController (IntPtr handle) : base (handle)
		{
		}
	}

	class SecuritiesTableSource : UITableViewSource
	{
		const string CellName = "SecuritiesCell";
	}
}
