#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Pengeplan.Droid.Resource", IsApplication=true)]

namespace Pengeplan.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Pengeplan.Droid.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Pengeplan.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_in2 = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int ptrsharp_sb_gradient_end = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ptrsharp_sb_gradient_start = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ptrsharp_sb_header_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ptrsharp_sb_header_text_shadow = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int depositories = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int history = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout2 = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int listView_depositories = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int listView_history = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int listView_securities = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int login = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int password = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int password_label = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int pie_container_id = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int pin = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int pin_label = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int refresher = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int remember = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int securities = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int splash_imageView = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int tabHost = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int transaction_list_cell_name = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int transaction_list_cell_value = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int transactionsListView = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int username = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int username_label = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int overview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int splash = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int transaction_list_cell = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int transactions = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int ErrorTitle = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int Loading = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int d_password = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int d_username = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int depositories = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int history = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int login = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int overview = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int password = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int pin = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int remember = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int securities = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int username = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
